### ISSUE TITLE
catch_that_image() について質問

### ISSUE THREAD

**Issue by shimakyohsuke** [wckansai2016/for-the-future#10]
https://github.com/wckansai2016/for-the-future/blob/master/functions.php#L56
catch_that_image() こういうの見たなー

[[WordPress] 記事中の最初の画像を自動検出して表示](http://memo.dogmap.jp/2011/07/13/%E8%A8%98%E4%BA%8B%E4%B8%AD%E3%81%AE%E6%9C%80%E5%88%9D%E3%81%AE%E7%94%BB%E5%83%8F%E3%82%92%E8%87%AA%E5%8B%95%E6%A4%9C%E5%87%BA%E3%81%97%E3%81%A6%E8%A1%A8%E7%A4%BA/)

でも、いいやりかたどなたか知りませんか？

**Comment by torounit** [comment]
`
ob_start();
ob_end_clean();
`

はいらんぞ・・・という話はさておいて。

添付されている画像を `get_children()` で取ってきて、みたいな奴ですかね。

[関数リファレンス/get children - WordPress Codex 日本語版](http://wpdocs.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/get_children#.E6.8A.95.E7.A8.BF.E3.81.AB.E6.B7.BB.E4.BB.98.E3.81.95.E3.82.8C.E3.81.9F.E6.9C.80.E5.88.9D.E3.81.AE.E7.94.BB.E5.83.8F.E3.82.92.E8.A1.A8.E7.A4.BA)

**Comment by shimakyohsuke** [comment]
`get_children()` これは知らなかった。これで良さそう。
あとはアイキャッチも投稿内の画像もないときに「No Image」画像だせるようにすればいい感じっすかねー

**Comment by torounit** [comment]
あと、3.6だか3.7だかで、それっぽい関数が追加されて削除された記憶があるからちょっとレポジトリ潜ってみます。

**Comment by torounit** [comment]
あったあった。これこれ。

https://github.com/WordPress/WordPress/commit/769e3e9b5decd7798369ac7be75651d8f0be4510

**Comment by shimakyohsuke** [comment]
よく覚えてますね。。
取り急ぎ `get_children()` を使用していればOKってことですねー

**Comment by torounit** [comment]
get_children だと、既に既存の投稿やページに紐付いている奴はとれないんですよね。それを避けようと思うと、どうしても本文欄から正規表現で取ってくる必要が出てきたりですね。

まぁ、そこまでやるなら本文欄から画像取ってきて自動でサムネイル設定するプラグイン使えよって話になるのかもしれません。どうなんだろう。

**Comment by shimakyohsuke** [comment]
そもそもこの機能が必要なのかってことっすね。アイキャッチ表示させるだけでOKと思う。

**Comment by natashat** [comment]
https://github.com/wckansai2016/for-the-future/pull/51
