### ISSUE TITLE
< 782 以下の時に 管理バーの上に隙間が空く。

### ISSUE THREAD

**Issue by torounit** [wckansai2016/for-the-future#142]
### 求めている動作

隙間をなくす
### 現状の動作

![2016-03-27 1 06 34](https://cloud.githubusercontent.com/assets/1908815/14060998/30d56038-f3b8-11e5-973f-7a8317b4c5d9.png)
### 原因

bodyにposition relative がついてる。

**Comment by shimakyohsuke** [comment]
#208 で対応済み
