### ISSUE TITLE
style.cssのdescriptionを英語に

### ISSUE THREAD

**Issue by hideokamoto** [wckansai2016/for-the-future#152]
### 概要

https://github.com/wckansai2016/for-the-future/blob/master/src/styles/style.scss#L8
ここ英語で説明書いておかないとレビューで突っ込まれますね・・・
### 求めている動作

英語でテーマについての説明文が書かれてる
### 現状の動作

日本語でダミーがある
### 原因

初期状態のまま
### 対処

誰か書こーぜ

**Comment by shimakyohsuke** [comment]
@hideokamoto 
これは @natashat さんが考える事になってます！
