### ISSUE TITLE
autoprefixer があるので Sass/SCSS ファイルにはベンダープリフィクスがいらない

### ISSUE THREAD

**Issue by shimakyohsuke** [wckansai2016/for-the-future#154]
### 概要

ついてても問題はないので、優先度低めで

https://github.com/wckansai2016/for-the-future/blob/master/src/styles/modules/_site-footer.scss#L19-#L20

**Comment by potato4d** [comment]
この辺ってautoprefixer良さ気にしてくれましたっけ。
https://github.com/wckansai2016/for-the-future/blob/master/src/styles/base/_elements.scss#L120-L128

**Comment by hinaloe** [comment]
``` scss
&::placeholder {
    color: #b0b0b0;
}

```

でよさそう

http://autoprefixer.github.io/
