### ISSUE TITLE
マークアップ: HTML タグとフォーマット

### ISSUE THREAD

**Issue by hinaloe** [wckansai2016/for-the-future#167]
### 概要

各HTML要素に対するスタイルシートが未実装
### 参考

日本語版テストデータ：
「マークアップ: HTML タグとフォーマット」(スラッグ：markup-html-tags-and-formatting)

**Comment by torounit** [comment]
とりあえず base/elementsをそれっぽくすればええんやないかと。

**Comment by hideokamoto** [comment]
pre / q / code あたりあればとりあえずOK・・・？
