### ISSUE TITLE
コメントスレッドのスタイル

### ISSUE THREAD

**Issue by hinaloe** [wckansai2016/for-the-future#170]
### 概要

スレッド化されたコメント(返信コメント)は視覚的に分かるようにすべき
### 求めている動作

スレッド化されたコメントの親子関係が見える
### 現状の動作

全て縦一列
### 参考

参考にするテストページ等：[テンプレート：コメント] `template-comments`

TwentySixteenの場合 ：
<img width="790" alt="2016-03-30 2 41 12" src="https://cloud.githubusercontent.com/assets/5253290/14117732/f6673e42-f620-11e5-8e0b-5fc6d6f2d92b.png">

**Comment by potato4d** [comment]
Done.
