### ISSUE TITLE
フッター：サイト名が長い(2行以上に渡る場合)はみ出る

### ISSUE THREAD

**Issue by hinaloe** [wckansai2016/for-the-future#178]
### 概要

フッターテキスト(主にコピーライトの部分)が`.site-footer`からはみ出る
### 求めている動作

はみ出ない
### 現状の動作

<img width="335" alt="2016-03-30 22 47 41" src="https://cloud.githubusercontent.com/assets/5253290/14144612/5e0c85fc-f6cb-11e5-968a-a37c44ce1eeb.png">
<img width="1134" alt="2016-03-30 22 56 25" src="https://cloud.githubusercontent.com/assets/5253290/14144613/5e5b5baa-f6cb-11e5-99da-896e89595641.png">
### 原因

`height: 13em`決め打ちのため
### 対処
- [ ]

**Comment by shimakyohsuke** [comment]
`.site-footer` の `height: 13em` を  `min-height: 13em` に変更じゃと思ったら、
`.index-nav-links-wrapper` の親要素の `.l-grid` の `margin:-16px` が邪魔するでござる。

**Comment by shimakyohsuke** [comment]
https://gyazo.com/84a2397830cd613d71734bb31edac2c1

**Comment by shimakyohsuke** [comment]
#208 で対応済み
