### ISSUE TITLE
フッターの固定のためのstyleがelementsに書かれてる

### ISSUE THREAD

**Issue by torounit** [wckansai2016/for-the-future#184]
関連 #142 

そもそも layout でやっつける問題であって、base でやってはいけなかった。。。CSSの汎用性、テストのしやすさを大きく損なうので、要修正。

**Comment by shimakyohsuke** [comment]
@torounit 
これってこの状態がよくないってことですか？？

`<footer class="site-footer">`

**Comment by shimakyohsuke** [comment]
#208 で対応済み
