### ISSUE TITLE
.comments-areaのスマホ対応について(元：〃がスマホの時右に寄ってる。）

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#186]
### 概要

コメントのブロックが、ブラウザ幅が狭い時に右に寄っている。
### 求めている動作

コメントブロックも中央配置。
### 現状の動作

comments-areaが右に寄っているので「Comment」の文言が中央に配置されていない。

**Comment by potato4d** [comment]
そもそもコメント自体色々とPCとスマホで違っていて、未実装なので、バグ云々じゃないですね。
こちらでやります。

**Comment by natashat** [comment]
スマホで見たときのコメント欄についても #253 のデザインに合わせてコーディング時に対応する。
こちらのissueは一旦クローズ。
