### ISSUE TITLE
スマホの時ページネーションがレイアウト崩れする。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#189]
### 概要

ブラウザ幅が狭い時ページネーションがレイアウト崩れする。(ページ番号が2など表示要素が多い時)
### 求めている動作

・・・どうしましょ。
### 現状の動作

ブラウザ幅が狭い時ページネーションがレイアウト崩れする。(ページ番号が2など表示要素が多い時)
### 原因

ブラウザ幅が狭いため。

**Comment by natashat** [comment]
あ、デザイン上はPREVとNEXTと現在ページ番号表示だけでしたね。すみません、今確認しました。
実装方法考えます。

**Comment by natashat** [comment]
現状、例えばiPhone5の場合
<img width="320" alt="2016-08-27 21 34 54" src="https://cloud.githubusercontent.com/assets/3609038/18027430/434849ec-6c9e-11e6-94a6-754ffe604a63.png">
こんな感じです。
PREVとNEXTが両方出る状態になると、幅的に入りきらない状況です。

**Comment by torounit** [comment]
あきらめて小さい画面のときは、数字を消すのはどうでしょう？

**Comment by chimiochimio** [comment]
これ5ヶ月前に「PREVとNEXTと現在ページだけの表示」と認識してもらってますよね？ですが、その後のキャプチャーみたらページ番号減ってないですが実装方法無かったんですか？技術的にページ番号を現在ページだけに出来ないのであれば、PREVとNEXTだけでいいです。

**Comment by natashat** [comment]
PREVとNEXTだけにしてはということですね。
私は一覧の場合は全体で何ページなのかは見たいと思うのですが、そういう需要はない(少ない)ということでしょうか？
できれば他の方のご意見もお聞きしたいです。

**Comment by chimiochimio** [comment]
正直5ヶ月前のワイヤーに書いた指示に対してその時に何の意見もない状態で今まで来て、その後自分の主観をデザインに持ち込んで、実装出来ないからその方法考えてくれってのは僕は納得いかないです。
他人に意見を求めるなら、自分の考える実装方法をまず提示してください。

**Comment by natashat** [comment]
@chimiochimio えーと、ワイヤーフレームにはもともとFIRST LASTへの導線があったんですね。それがデザインの時点でなくなってたんです。でもWPのテンプレート関数を使えば通常の出力はこんな風(上図)になるからFIRST LASTへの導線が確保されるのでそれでOKだね。というやりとりは確かチミヲさんとしたと思うんですが。(その時はSPのことはお互い考えから抜けていたと思います。)
私の案としては、こんな感じはどうでしょうか。
![img_3181](https://cloud.githubusercontent.com/assets/3609038/18031971/9ae42066-6d31-11e6-9d4e-996f09917ae6.JPG)

**Comment by chimiochimio** [comment]
「FIRST LASTの表示」の件はPC版の話ですよね？このissueでの問題はSP版の話ですよ。それに「FIRST LASTの表示」もSP版のワイヤー見てますが、それに対して表示を行うように指示書いてませんから、考えから抜けていたの表現もおかしいのではないですか？

それはいいとして、自分で実装後のイメージがあるならそれで実装して、今挙がっている問題を解決してください。

他の方の意見も何もこの表示にしたいのはナターシャの考えから来ているものですよね？さっきから言っているように、他のページを表示にするように指示は書いていませんし、SP版のデザインカンプでも僕が指示を出した通りの記載になっています。

自身の判断で変更するならば、自身の責任に於いて行ってください。これが僕の意見です。ハングアウトには参加しません。

**Comment by yat8823jp** [comment]
ちみさんがおっしゃってくださっているように、もともとの実装予定となっている「PREVとNEXTと現在ページだけの表示」で問題ないと思います。
ハングアウトも必要ないかと。

**Comment by natashat** [comment]
すみません、私がPCとSPでの実装を混同して、お騒がせしたみたいで。
PREVとNEXTと現在のページ番号の表示、でいきますね。
ご意見ありがとうございました。

**Comment by yat8823jp** [comment]
よろしくお願いしますー
