### ISSUE TITLE
実装順について

### ISSUE THREAD

**Issue by potato4d** [wckansai2016/for-the-future#195]
### 概要

実装順がごっちゃごっちゃでよーわからん
### 求めている動作

何かPCとかスマホとかごっちゃじゃなくて、完全に並行なのか順番なのかとか決めてつくる
### 現状の動作

気分次第
### 原因

みんなの気分
### 対処

話そう

**Comment by shimakyohsuke** [comment]
@potato4d 
labelsの「bug」でマイルストーンBeta Release から順番につぶしていくってのがあるけど、
このBeta Release付与の基準がPCとスマホの関係の事を考えて付与してるのか？ってことが問題なわけですよね？

**Comment by potato4d** [comment]
@shimakyohsuke 
取り敢えず今はBeta Releaseが優先/Low Priorityが優先しないタスクになっていますけど、
それだけでやっているので、PC対応のみ先に書いているのか、スマホも含めてなのかがわかりづらいみたいなところですね。
例えばそもそも未実装の部分を「bug」ラベルを付与するのは適切ではないですし、「enchantment」でやるべきじゃないか。という話になりますし。

……これ以上会話する人が増えるとSlackでチャンネル建てたほうが良さそうな問題ですね。

**Comment by hinaloe** [comment]
そもそもBeta Releaseを使い続けてることに違和感を感じてなくなかったり(でもまだ状態的にはあれだから別にその問題はいいか…………)

2016年4月11日(月) 12:42 Potato4d(Hanatani Takuma) notifications@github.com:

**Comment by hideokamoto** [comment]
４月中旬くらいからセッションチーム勢にセッション・ハンズオンタスクをガンガン振っていくことになるかと思うので、コミット率下がるかも。

**Comment by hideokamoto** [comment]
・表示が大きく崩れる
・動作しなくなる
・どう考えてもレビューで突っ込まれる

この辺りを優先度高にして

・デザイン上対応したい
・あると嬉しい
・感覚的に気になる

この辺りは優先度下げてしまったほうがいいかと。
気になる・良くしたいのはわかりますが、WordCamp Kansaiのタスクはこれだけではないので。

**Comment by potato4d** [comment]
MTGにて方針が決定したので〆。
（詳細はBacklog及びDocs参照）
