### ISSUE TITLE
製作状況管理用

### ISSUE THREAD

**Issue by potato4d** [wckansai2016/for-the-future#209]
### PC版
- [ ] トップページ
- [ ] アーカイブページ
- [ ] Postページ
- [ ] 固定ページ
### SP版
- [ ] トップページ
- [ ] アーカイブページ
- [ ] Postページ
- [ ] 固定ページ
### コンポーネントPC
- [ ] ヘッダー
- [ ] ナビゲーション
- [ ] フッター
- [ ] コメント
### コンポーネントSP
- [ ] ヘッダー
- [ ] ナビゲーション
- [ ] フッター
- [ ] コメント

**Comment by natashat** [comment]
PC版表示チェック完了。タスクが結構発生。

**Comment by natashat** [comment]
SP版 singularの表示チェック完了。(ChromeのエミュレーターiPhone6で)
ただし
・コメントは含まない。
・PCの修正で直ると思われる部分は含まない。

**Comment by potato4d** [comment]
これ（チェックリストとして）使われてないので消しますね。
