### ISSUE TITLE
PCブラウザ幅広い時：トップへ戻るボタンが右過ぎる・・・

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#211]
### 概要

PCブラウザ幅広い時：トップへ戻るボタンが右過ぎる・・・
### 求めている動作

コンテンツ幅のちょい右ぐらいがベスト。
### 現状の動作

右固定なのでブラウザ幅が広いとボタンを探してしまう。(初見の人は存在に気づかないかも)

**Comment by potato4d** [comment]
うーん、大抵どのサイトもこういう感じだしなぁという印象。
ただ、1280pxの中でうまいことやるのも良さそうなので、今デザインやる中で色々やっていきますー。

**Comment by potato4d** [comment]
Slackの流れとして

> 了解ですー。これはとりあえず現状のままでいいかな。機能してない訳じゃないので置いておきましょう。

のようなので、取り敢えず１回テーマとして出した後に処理していきましょうか。

**Comment by natashat** [comment]
急ぎではないですが、フィードバック返ってくるまでにできそうならやっときましょうか。

**Comment by potato4d** [comment]
これ割りとやっぱり画面右端に近いのがデファクトかと思いますがどうでしょ？（とりあえずたまたま見てたURLだけ貼っておきます）

http://techacademy.jp/magazine/
http://laravel.jp/

**Comment by natashat** [comment]
私がiMacのフルサイズで見てるからというのもあるかもしれませんが、挙げてもらったサイトとコンテンツ幅が結構違うので比較し難いなぁ、と。

ただiMacのような広い画面だとブラウザの高さもそこそこあるので、一覧の表示投稿数がデフォルトの場合、一覧ではほとんど必要なくてsingularでコンテンツが長い場合のみで必要になるボタンだと思います。
となるとギャラリーという特性上できる限りコンテンツと離す(ブラウザ右端に配置する)のは正解のような気もします。

特に異論がないようでしたら、一旦クローズとしたいと思います。

**Comment by shimakyohsuke** [comment]
@natashat 

> 私がiMacのフルサイズで見てるからというのもあるかもしれませんが、挙げてもらったサイトとコンテンツ幅が結構違うので比較し難いなぁ、と。

ちょっと話それますが、ブラウザのウィンドウサイズを世に出てるディスプレイ規格のサイズに変えてくれるChrome拡張とか使えばなんとなくわかると思いますよ。
https://chrome.google.com/webstore/detail/resolution-test/idhfcdbheobinplaamokffboaccidbal

個人的には 1366px - 768px のウィンドウを基準にしてますねー

一旦クローズでOKかとー

**Comment by natashat** [comment]
クローズします。
