### ISSUE TITLE
コメント：必須入力チェックはjQuery(画面遷移しない)がいい。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#214]
### 概要

コメント：必須入力チェックはjQuery(画面遷移しない)がいい。
### 求めている動作

必須入力チェックは画面遷移なしでやってほしい。戻るボタンはできるだけクリックさせたくない。
### 現状の動作

画面遷移(php)

**Comment by hinaloe** [comment]
WordPressの仕様です(何故かhtml5になってるときはバリデーション無効化する)

テーマの管轄外。
