### ISSUE TITLE
singular:タイトルにマークアップがあった時に反映させる。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#217]
### 概要

テストデータ「markup-title-with-markup」によるとタイトルにマークアップがあった時には反映させること、と。斜体など。
### 求めている動作

タイトルにマークアップがあった場合、表示にマークアップを反映させる。
### 現状の動作

ソース上平文になっている。

**Comment by hinaloe** [comment]
テストデータの問題ですね。試してみたけどHTMLとしては正常に反映されます。`strong`は`h1`が元からfont-weight:boldを持ってるため見ても差がない状態にはなりますが。

**Comment by hinaloe** [comment]
ん?これもしかしてアーカイブの方の話ですか?となるとこれはどっちかといってstrip_tagsさせて……って話になるのかな、そもそも`mb_substr`してるのがアレだけど……
