### ISSUE TITLE
コメント：ページ送りが発生した時に、デザインされてない感

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#218]
### 概要

コメントが1ページの表示件数を越えた時に表示されるページ送りが、テキストそのまま出てる感じなので、他のページ送りと同様にした方がよいかも。
### 求めている動作

&lt;PREV NEXT&gt;のような他と同じページ送りのデザイン。
### 現状の動作

Older Comments、Newer Commentsとコメントの両端上部に表示される。

**Comment by potato4d** [comment]
template-commentsでコメントのページ送りサンプルがなくて現象が確認できないので、確認できるサンプルが用意でき次第対応します。

取り敢えずそれまでは置いておくことで。（スクショがあればありがたい）

**Comment by potato4d** [comment]
これそもそも機能知らなかった（）ので今着手中のコメント欄で一緒にやりますー。
失敬。
