### ISSUE TITLE
.nav_btn は button

### ISSUE THREAD

**Issue by torounit** [wckansai2016/for-the-future#22]
class で btn って書いてあるってことは <button /> タグでマークアップすべき事案！

**Comment by shimakyohsuke** [comment]
button.nav_btn ってこと？

**Comment by torounit** [comment]
せやで！！！

**Comment by shimakyohsuke** [comment]
自分は button タグ以外でも btn って class 作っちゃうな―

**Comment by hinaloe** [comment]
どっちにしてもボタンはbutton使えって(どっかに記事あったから貼ろうと思ったけど見つけられなかった)

**Comment by natashat** [comment]
https://github.com/wckansai2016/for-the-future/commit/cd831a1118ef8fa7760d3f7d32df587b2b082af8
