### ISSUE TITLE
singular:Jetpack のタイルギャラリーの表示

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#220]
### 概要

テストデータ「post-format-gallery-tiled」より、Jetpackのタイルギャラリーの表示テストがありましたが、画像のリンクをクリックすると元のページに戻れない不具合。ていうかこれ対応しないといけないんでしょうか。未確認。

**Comment by hinaloe** [comment]
手元で確認してみて問題が見受けられなかったのですが詳細を明記していただけますか?

そもそもJetpackを有効化していますか?

(対応は必須ではないはずです。)
