### ISSUE TITLE
ドロワー：スマートフォン対応

### ISSUE THREAD

**Issue by potato4d** [wckansai2016/for-the-future#224]
### 概要

スマートフォン対応がされていない
### 求めている動作

スマートフォン対応がされる
### 現状の動作

されていない

**Comment by natashat** [comment]
スマートフォン対応って具体的に何でしょうか？

**Comment by potato4d** [comment]
%指定されているからちょろっとしか出てこなくて何も出来ない現象ですね（この当時から状況が変わっているので治っている可能性アリ）

**Comment by potato4d** [comment]
どこかのタイミングで治ったようなので〆
