### ISSUE TITLE
singular:SP:カテゴリ、タグの幅が狭すぎる。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#232]
### 概要

singular:SPで見た時カテゴリ、タグの幅が狭すぎる。width:80%;ぐらいあってもいいような。
### 求めている動作

カテゴリ、タグが長い、多い場合もある程度見やすい幅
### 現状の動作

幅が40%で、カテゴリー、タグが長い、多い場合に見にくい。また無駄な高さを取る。

**Comment by potato4d** [comment]
80%でいきましょうか。
