### ISSUE TITLE
[Theme check]隠しファイルもしくは隠しフォルダ が見つかりました。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#246]
### 概要

警告: .ds_store .editorconfig .git .github .gitignore .travis.yml .bin .npmignore .gitattributes .tern-project .keep .jshintrc .zuul.yml .test .gitkeep .eslintrc .babelrc .deps .cardinalrc .coveralls.yml .testem.json .lint .jscsrc .eslintrc.js .lintignore .gitignore.orig .gitignore.rej .jscs.json .tern-port .gitmodules .ignore .dir-locals.el .eslintignore .jamignore .dntrc .build.sh .npmrc .idea .name .verb.md .jshintignore .history.md.un~ .package.json.un~ .readme.md.un~ .index.js.un~ 隠しファイルもしくは隠しフォルダ が見つかりました。
### 対処

最後に消す

**Comment by torounit** [comment]
申請出すのはdistブランチのはずなので、distブランチでこの警告が出なければ大丈夫のはず！
