### ISSUE TITLE
アップロード申請時に指摘のあったCSSのdescription

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#248]
### 概要

RECOMMENDED: This theme contains no sidebars/widget areas. See Widgets API
WARNING: The tag white has been deprecated, please remove it from your style.css header.
WARNING: The tag responsive-layout has been deprecated, please remove it from your style.css header.
WARNING: The tag light has been deprecated, please remove it from your style.css header.
WARNING: The tag gray has been deprecated, please remove it from your style.css header.
WARNING: The tag fluid-layout has been deprecated, please remove it from your style.css header.
WARNING: The tag black has been deprecated, please remove it from your style.css header.
RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
INFO: Only one text-domain is being used in this theme. Make sure it matches the theme's slug correctly so that the theme will be compatible with WordPress.org language packs.
The domain found is for-the-future
### 対処

対応しました。

**Comment by torounit** [comment]
#249
