### ISSUE TITLE
Font Awesome の配置、読み込みはどうすべき？

### ISSUE THREAD

**Issue by hinaloe** [wckansai2016/for-the-future#25]
- enqueueで単独で読み込み、ディレクトリは `assets/font-awesome/` など
- scss で合わせてコンパイルしてしまう
  - どうやってリポに入れる？npm?
- その他（ゆるぼ）

**Comment by torounit** [comment]
wp_enque_styles するべきかなと思います。プラグインなどで呼ばれていた場合、2重に読み込まれるのを防げるので。

**Comment by hinaloe** [comment]
(まぁちゃんと同名のスラッグ使ってくれてればだけどｗ)同意。

**Comment by torounit** [comment]
まぁ、マナーの良いプラグインとは相性が良いってことで良いんじゃ無いですかね。いつかコアに入るかもしれないしｗ

**Comment by hinaloe** [comment]
#122
