### ISSUE TITLE
テーマアップロード用にstyle.cssのバージョンをアップしました。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#250]

**Comment by potato4d** [comment]
これはなんですか？

**Comment by natashat** [comment]
.orgにアップロードする時にCSSの最初の部分のコメント部分でバージョンを前より上のものにしないとアップロードできないのですー。
というわけで変わったのはCSSの最初のコメント部分だけです。

**Comment by potato4d** [comment]
了解です。
もうみんなpending間が長すぎてよーわからんことになってますので、詳細書いていきましょう。
PRマージしますね。

**Comment by potato4d** [comment]
Close.
