### ISSUE TITLE
コメント欄のデザイン修正

### ISSUE THREAD

**Issue by potato4d** [wckansai2016/for-the-future#253]
### 概要

マイルストーンとかバラバラだしいい加減わかりづらいのでいっそまとめました
### 求めている動作

・コメント：ページ送りが発生した時に、デザインされてない感( #218 )
・コメント：第一階層目の返信は罫線を入れるなどわかりやすい工夫を。( #216 )
・コメント：返信時のインデントが微妙すぎて誰が誰にコメントしてるかわかりづらい。( #215 )
### 現状の動作

これらが解決されていない

**Comment by potato4d** [comment]
![web 1280 1](https://cloud.githubusercontent.com/assets/6993514/17333547/cad36684-590d-11e6-8b8c-dd5ba1b188be.png)

**Comment by natashat** [comment]
「編集　返信　編集　削除」の部分の出力される文言を確認。(コーディングベースで)
あとはこのデザインでフィックス。(PSDはない)
