### ISSUE TITLE
.stickyのCSSを制作

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#265]
### 概要

(テーマレビューより).sticky(先頭固定表示)であることがわかるCSSが必要との指摘を受けた。
### 求めている動作

外観から.sticky(先頭固定表示)の投稿であることがわかる。
### 現状の動作

.stickyのCSSが準備できておらず外観から区別がつかない。
### 対処

.stickyのCSSを制作

**Comment by natashat** [comment]
着手中

**Comment by yat8823jp** [comment]
対応済み
