### ISSUE TITLE
タブレットサイズ以下、アーカイブ表示時タイトルの下に余白を設ける

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/for-the-future#268]
### 概要

アーカイブ時タイトル下に余白がないため、タイトルが上の写真にかかっているのか、下の写真にあっ買っているのか分かりづらい。
### 求めている動作

タイトルの下に余白を設ける
### 現状の動作

余白指定なし
### 対処

.has-post-thumbnail {
    margin-bottom: 15px;
}
ぐらい

**Comment by natashat** [comment]
対応済み
