### ISSUE TITLE
REQUIRED: Use `the_posts_pagination()`

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#285]
### 概要
* REQUIRED: Use `the_posts_pagination()` for pagination rather than
 `paginate_links()`. `index.php`

**Comment by shimakyohsuke** [comment]
@natashat 

```php
					$temp_dir = esc_url( get_template_directory_uri() );
					$args     = array(
						'show_all'  => false,
						'end_size'  => 1,
						'mid_size'  => 1,
						'prev_next' => true,
						'prev_text' => '<i class="fa fa-angle-left"></i> PREV',
						'next_text' => 'NEXT <i class="fa fa-angle-right"></i>',
					);
					echo paginate_links( $args );
```
`paginate_links( $args );` を `the_posts_pagination( $args )` に変更かと思いますが、
`$temp_dir = esc_url( get_template_directory_uri() );`
これもいらないっすよね？

あと、[paginate_links](https://codex.wordpress.org/Function_Reference/paginate_links) と[the_posts_pagination](https://codex.wordpress.org/Function_Reference/the_posts_pagination) みると、パラメーターいくつか無くなっていたので、表示確認して消去しますね
