### ISSUE TITLE
REQUIRED: Theme tags - Add appropriate theme tags available.

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#289]
### 概要
 * REQUIRED: Theme tags - Add appropriate theme tags available. You can
 keep `blog` in theme tags. See in detail:
 https://make.wordpress.org/themes/handbook/review/required/theme-tags/ You
 can keep `theme-options` as you are giving option for footer image.

**Comment by natashat** [comment]
CSSのTheme tagsにblogとtheme-optionsを追加しました。

・・・けどなぜかプルリクできず。

**Comment by hinaloe** [comment]
@natashat  distから切ったでしょ……

**Comment by natashat** [comment]
すみません、ブランチ間違いました。
#284 のブランチで作業してしまいました。
プルリク #296

**Comment by natashat** [comment]
プルリクし直しました。#298
