### ISSUE TITLE
ドロワーの修正

### ISSUE THREAD

**Issue by hinaloe** [wckansai2016/for-the-future#30]
多分現在まだガワも途中なのだろうで深く突っ込んではいけないのだろうけどとりあえず 5f92fde 時点で気になった感じ
- [x] wp_nav_menu を突っ込むとスタイルが当たらない
- [x] #26 
- [x] スタイルのグローバル汚染(？)
- [ ] 検索窓わかりにくくない？
- [ ] レスポンシブ対応
- [x] [register_nav_menu の重複](https://wckansai2016.slack.com/archives/create-theme/p1458137358000709)
- [x] #95 
- [x] #112 

(dev/drawerとかいうよくわからないブランチを作ってしまったのでどうとでもしてください（（)

**Comment by torounit** [comment]
wp_nav_menu に関しては _s とかぱくってもいいきがしてるけど逆にそれもそれでつらいのかな。難しい。

**Comment by potato4d** [comment]
これが残っているとドロワーが管理しづらいので〆ます。
