### ISSUE TITLE
REQUIRED: Update `readme.txt` to keep credits and license info

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#302]
### 概要
 * REQUIRED: Update `readme.txt` to keep credits and license info. Keep
 credits for all third party resources. Keep full image URL of each images
 used in the screenshot. Sample format:
 https://make.wordpress.org/themes/2015/04/29/a-revised-readme/

**Comment by shimakyohsuke** [comment]
## YATさん（ yat8823jp ）だけ @ がない

```
Contributors: @natashanatashanatashanatasha, @kimio-nakanishi, @toro_unit, @shimakyohsuke, @potato4d, @hnle, @mayum, yat8823jp
```

## Themeに組み込まれてる画像に対してのライセンス表記例

<https://github.com/mismith0227/wp-theme-modernize/blob/master/readme.txt>

```
== Copyright ==
modernize WordPress Theme, Copyright 2015 Takuma Misumi
modernize is distributed under the terms of the GNU GPL

images/1.jpg, 2.jpg used in the screenshot is taken by the theme author and is released under GPL.
```

## 以下は削除

`Short description. No more than 150 chars.`
`== Frequently Asked Questions ==`
`= A question that someone might have =`

## Third Party Resources 表記例

<https://github.com/mismith0227/wp-theme-modernize/blob/master/readme.txt>

```
/* Third Party Resources
/* -------------------------------------------------------------- */

Normalize.css
License: MIT
Source : https://necolas.github.io/normalize.css/
```

For the future は以下がサードパーティかと。

- normalize.css
- font awesome

**Comment by shimakyohsuke** [comment]
## ライセンスのバージョンを合わせる

style.css には

```
License: GNU General Public License v3 or later
License URI: http://www.gnu.org/licenses/gpl-3.0.html
```

ですけど、readme.txt には

```
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
```

style.css に記載されているライセンスに合わせる
