### ISSUE TITLE
スクリーンショットで使用している画像の管理方法

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#313]
### 概要
選択肢1. 外部サービスに置く。
選択肢2. githubのmasterブランチで管理(distにはコピーしない)
https://github.com/wckansai2016/for-the-future/blob/master/gulp/tasks/dist.js

### 求めている動作
みんながアクセスできるオープンな場所に置く。

### 現状の動作
masterからdistにコピーされるが、ファイル容量が重すぎて公式ディレクトリにはアップロードできない。

**Comment by shimakyohsuke** [comment]
<https://github.com/wckansai2016/for-the-future/blob/master/gulp/tasks/dist.js#L12>

を以下にすれば、`./screenshots/` 含む配下のファイル・フォルダはdistフォルダに含まれないです。

```js
gulp.task('copy', function() {
	return gulp.src(
			[
				'./**/*.*',
				"!./.github/**",
				"!./dist/**",
				"!./bin/**",
				"!./gulp/**",
				"!./gulpconfig.js",
				"!./gulpconfig.js.sample",
				"!./gulpfile.babel.js",
				"!.travis.yml",
				"!.gitignore",
				"!.editorconfig",
				"!.github/**",
				"!composer.json",
				"!bower.json",
				"!package.json",
				"!./node_modules/**/*.*",
				"!./screenshots/**/*.*"
			],
			{ base: './' }
		)
		.pipe( debug() )
		.pipe( gulp.dest( 'dist' ) );
} );
```
