### ISSUE TITLE
header.php の meta viewport の値を変更する必要がある

### ISSUE THREAD

**Issue by shimakyohsuke** [wckansai2016/for-the-future#325]
### 概要

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
```
https://github.com/wckansai2016/for-the-future/blob/master/header.php#L5

`user-scalable=0` いらない

### 求めている動作

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

だけでよさそう

**Comment by yat8823jp** [comment]
detail を見るとphp5.3でエラーが出てるっぽいけど、これかぁ
しかし、どうしたらいいのやら・・・

**Comment by torounit** [comment]
https://blog.shimabox.net/2017/08/17/travis-ci_failed_hhvm_test/

travis が提供するイメージが変更点された影響のようです

**Comment by yat8823jp** [comment]
完了したので閉じます
