### ISSUE TITLE
HTML/CSSにおける class 命名の不一致

### ISSUE THREAD

**Issue by torounit** [wckansai2016/for-the-future#4]
ハイフン区切りと、アンダーバー区切りが混在してます。
WordPress に習って、ハイフンで統一すべし！

**Comment by shimakyohsuke** [comment]
こちらは関数名はアンダースコア
テキストドメインはハイフン区切り
で統一すればいんですよね？

**Comment by shimakyohsuke** [comment]
これはもしや、CSSのお話？？

**Comment by torounit** [comment]
CSSの話ですね。ちょっとタイトル変えましょう。
