### ISSUE TITLE
headのタグ順と閉じ/の統一

### ISSUE THREAD

**Issue by potato4d** [wckansai2016/for-the-future#40]
meta(keywords, description), meta(その他), link順がベターかな？
閉じタグが必要ないタグの閉じスラッシュはアリナシ統一した方が綺麗かも。

優先度も最低クラスですし構築の最後にまとめてで問題なさそう。

**Comment by shimakyohsuke** [comment]
順番はWPサイトの場合、こだわるとつらそう。

> 閉じタグが必要ないタグの閉じスラッシュはアリナシ統一した方が綺麗かも。

これはやるべし
