### ISSUE TITLE
NoImageのサイズが大きすぎる。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#55]
### Expected Behavior

一覧で画像が並んだ時に文字などのコンテンツがトリミングされない。
### Actual Behavior

一覧で並んだ時にトリミングされて、文字などが切れる。
ただし、singleの時には全幅表示される予定なので、画像を小さくすればいいわけではない？
single用のと画像を二つ用意すべき？
### Environment
- OS: Write here
- npm version: Write here

**Comment by shimakyohsuke** [comment]
NoImages だけ `max-width:100%;` いれればOK！

```
<img style="max-width:100%;" src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/img_noimg.png" alt="<?php the_title(); ?>" />
```

**Comment by natashat** [comment]
style="width:100%;"をNoImageに当てました！
それでデザイン的に気づいたことはNoImageに枠線がほしいということです。grid感皆無になるんで。

**Comment by shimakyohsuke** [comment]
> style="width:100%;"をNoImageに当てました！

今回用意されている画像は大きいので `width:100%;` でもいいかと思いますが、
例えば子テーマにして NoImage 画像変更し、その画像がグリッドサイズより小さい場合 `width:100%;` にすると画像は引き伸ばされてしまいませんか？？

NoImage 画像のサイズがグリッドより小さい場合は、
- 小さい画像のまま、縦横センター寄せ（ `max-width:100%;` ）
- 小さい画像はグリッドサイズに合わせて引き延ばす（ `width:100%;` ）

どちらがいいすかねー？？

**Comment by potato4d** [comment]
アイキャッチ画像がない場合は、singularについてはNo Imageの画像無しで大丈夫です！

**Comment by shimakyohsuke** [comment]
@natashat 

> NoImageに枠線がほしいということです

こちらは画像で対応していただきましょう

> NoImage 画像のサイズがグリッドより小さい場合は、
> - 小さい画像のまま、縦横センター寄せ（ max-width:100%; ）
> - 小さい画像はグリッドサイズに合わせて引き延ばす（ width:100%; ）
> 
> どちらがいいすかねー？？

小さい画像はグリッドサイズに合わせて引き延ばす（ width:100%; ）でいきましょう！
なので現状のままでOKです！

> アイキャッチ画像がない場合は、singularについてはNo Imageの画像無しで大丈夫です！

こちらのみsingle.phpページで画像がない場合のheightの対応が必要となりますので、完了次第こちらクローズでお願いします！

**Comment by natashat** [comment]
> アイキャッチ画像がない場合は、singularについてはNo Imageの画像無しで大丈夫です！
> こちらのみsingle.phpページで画像がない場合のheightの対応が必要となりますので、完了次第こちらクローズでお願いします！

対応しました！クローズします。
