### ISSUE TITLE
CSSのモジュール化

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#56]
### Expected Behavior

style.scssに書かずにモジュール化する。
### Environment
- OS: Write here
- npm version: Write here

**Comment by potato4d** [comment]
@natashat 
まだ分割されていないの、clearfixとscreen-reader-textだけですが、特別style.scssに書いている理由ってありますかねー？
なければこれを分割したものをマージしてこのIssue終わりで良さそう。
