### ISSUE TITLE
メニュー項目のリンクはインライン？

### ISSUE THREAD

**Issue by hinaloe** [wckansai2016/for-the-future#58]
`display: inline` or `display: block` or other

<img width="363" alt="2016-03-17 23 01 51" src="https://cloud.githubusercontent.com/assets/5253290/13848277/70a3ff6a-ec94-11e5-9c41-cc213c5e1d13.png">
<img width="314" alt="2016-03-17 23 02 50" src="https://cloud.githubusercontent.com/assets/5253290/13848278/70a5211a-ec94-11e5-8d2c-74817561fc1e.png">

**Comment by torounit** [comment]
ブロックですね。inline-blockとかでも問題ないとはおもうけど。

インタラクション系はむしろ特別な理由が無い限りボックスがクリッカブルになる実装を選ぶべきっす。たいていの場合、ボタンとして機能してる側面が強いので。
