### ISSUE TITLE
singularで表示するアイキャッチを上下中央にしたい。

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#59]
### Expected Behavior

singularのアイキャッチは高さ400px固定。中央400pxを表示したい。
### Actual Behavior

普通にoverflow:hiddenすると上から400pxしか表示されない。
### Environment
- OS: Write here
- npm version: Write here

**Comment by potato4d** [comment]
こっちでやりまー。

**Comment by potato4d** [comment]
#145 にて解決する方向になったのでclose.
