### ISSUE TITLE
ブレークポイントどうする？

### ISSUE THREAD

**Issue by torounit** [wckansai2016/for-the-future#71]
モバイルと、タブレット、PCのデザインがあるけど、ブレークポイント何処にします？

とりあえず、
0~767,768 ~ 1023, 1024 ~ 

とかですかね。（適当）

**Comment by hinaloe** [comment]
ワイヤーに書いてる！

**Comment by shimakyohsuke** [comment]
ワイヤーに書いてる！

**Comment by torounit** [comment]
ほんとだｗｗｗ

foundationけいしきだー。しつれい。

640,1024 でぶった切る形式ですね。
