### ISSUE TITLE
index:画像hover時にタイトルを表示

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#75]
### Expected Behavior

画像hover時にタイトルを表示。
→タッチデバイスの場合タイトルを見る手段がないけどどうしましょう？
### Actual Behavior

未実装
### Environment
- OS: Write here
- npm version: Write here

**Comment by chimiochimio** [comment]
@natashat 
ナターシャさん。
hover時の対応は添付のPDF参照で対応ください。
質問などあればまたこちらに書いてください。よろしくですー。
[#75 index-画像hover時にタイトルを表示.pdf](https://github.com/wckansai2016/for-the-future/files/181378/75.index-.hover.pdf)

**Comment by natashat** [comment]
内容理解しました！

**Comment by natashat** [comment]
#42 #41 
現状、indexでサムネイルを正方形で出す部分が実装されていないので、そこが完了次第手をつけたいと思います。
と言いつつ、ここは優先度高いと思うので急ぎたいのですが、 @torounit さんどうでしょう？

**Comment by potato4d** [comment]
今確認しましたがタイトルを画像の下部にオーバーレイ表示とかどうでしょう？
この解決策は解決策でうーん……（未対応ならでいいですが
