### ISSUE TITLE
ヘッダーロゴカスタマイズ機能の実装

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#82]
### Environment
- OS: Write here
- npm version: Write here

**Comment by natashat** [comment]
> ヘッダーのロゴ画像の変更方法はどうやって実装すればいい？
> 「カスタムヘッダー」機能を使います。
> Codex：
> https://wpdocs.osdn.jp/%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%98%E3%83%83%E3%83%80%E3%83%BC
> 
> Habakiriさんの実装例：
> https://github.com/inc2734/habakiri/blob/master/functions.php#L58

・「ヘッダー画像」という文言がわかりづらい。→実際はロゴ画像
・#83 フッター用にヘッダーと異なるロゴ画像をアップしたい場合の実装方法がわからない。

以上の問題、解決できるでしょうか？

**Comment by hinaloe** [comment]
ロゴは Jetpack or 4.5 のロゴ画像とは別？
