### ISSUE TITLE
index:カテゴリーや検索結果などの条件表示

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#85]
### Environment
- OS: Write here
- npm version: Write here

**Comment by natashat** [comment]
indexって自動で検索キーやカテゴリー名を出力しちゃうみたいなんですが・・・。
何のタグにも囲まれていないのでスタイリングもできず・・・。
やっぱりarchive作らないとだめでしょうか。
動いてないですが、こういうことをやりたい・・・というソースをコミットしています。

**Comment by torounit** [comment]
serch_query みたいな関数があったような

**Comment by torounit** [comment]
ちょっとやります
