### ISSUE TITLE
footer.phpの作成

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#94]
### Environment
- OS: Write here
- npm version: Write here

**Comment by natashat** [comment]
バグありです。ソースのみ見てください。

・コンテンツが少ししかない時にfooterをブラウザ下部に固定させようとしていますが、footer分のスクロールが発生します。(こういう実装やったことあるんですけど、見つからない・・・)
・SNSのリンクについてウィジェットを利用しようとしていますが、勝手にdivタグが挿入されてhrefが機能しない。
・願わくば、SNSのURL入れる用のウィジェット(一行テキストボックス)がウィジェットエリアにセットされててほしい。「既存の「テキスト」ウィジェットをエリアに移動→タイトル無視してコンテンツ部分にURL入れてね。」は不親切すぎると思うので・・・。
・トップへのスクロール機能→忘れてた汗。明日やります。

よろしくお願いします。

**Comment by hinaloe** [comment]
SNSアイコンはウィジェットは使うべきではないと思います。(ウィジェット置くならその下にSNSアイコン)

多くの場合、カスタムメニューで対応してたりします。
(Habakiriの例
https://github.com/inc2734/habakiri/blob/master/footer.php#L27-L39
https://github.com/inc2734/habakiri/blob/2de37e61585659b913cf08918fb40591b7d48796/src/scss/layout/_footer.scss#L20-L145
)

**Comment by natashat** [comment]
Habakiri参考になりました！
URLでスタイル当て分けるとはね・・・。
Habakiri式でやってみます。

**Comment by natashat** [comment]
SNS、Habakiri方式でできました。(ついでにFontawesomeでサポートしてるサービスは踏襲しました。)
ありがとうございます。

> ・コンテンツが少ししかない時にfooterをブラウザ下部に固定させようとしていますが、footer分のスクロールが発生します。(こういう実装やったことあるんですけど、見つからない・・・)
> ・トップへのスクロール機能→忘れてた汗。明日やります。

が残ってます。
「トップへ戻る」の方から作業進めます。

**Comment by natashat** [comment]
#94 トップへ戻るボタン設置しました。

> ・コンテンツが少ししかない時にfooterをブラウザ下部に固定させようとしていますが、footer分のスクロールが発生します。(こういう実装やったことあるんですけど、見つからない・・・)

これちょっと後回しにします。

**Comment by natashat** [comment]
一旦PR送りました。

> ・コンテンツが少ししかない時にfooterをブラウザ下部に固定させようとしていますが、footer分のスクロールが発生します。(こういう実装やったことあるんですけど、見つからない・・・)

については別issue立てます。

**Comment by hinaloe** [comment]
> ・コンテンツが少ししかない時にfooterをブラウザ下部に固定させようとしていますが、footer分のスクロールが発生します。(こういう実装やったことあるんですけど、見つからない・・・)

対応できたんでコミットしますね
