### ISSUE TITLE
言語ファイルの作成

### ISSUE THREAD

**Issue by natashat** [wckansai2016/for-the-future#98]
### Expected Behavior

そんなに数はないと思いますが、最終的に言語ファイルを作成。
英語と日本語だけでいいですよね？
### Environment
- OS: Write here
- npm version: Write here

**Comment by hideokamoto** [comment]
翻訳ファイルは必須ではないので、余裕があればでいいと思います。

**Comment by potato4d** [comment]
英語の原文は必要ですが、英語 to 日本語の翻訳については、org側でできるシステムがあるので、無理にこっち(create-theme)でやる必要はなかったり。

**Comment by natashat** [comment]
> 英語の原文は必要ですが、英語 to 日本語の翻訳については、org側でできるシステムがあるので、無理にこっち(create-theme)でやる必要はなかったり。

であれば、特にやる必要はなさそうですね。
異論がなければクローズしようと思います。

**Comment by natashat** [comment]
クローズします。
